source 'https://rubygems.org'
ruby '2.4.1'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-activerecord'
gem 'rack-contrib'
gem 'rack-ssl'
gem 'rack-throttle'
gem 'activerecord'
gem 'activesupport'
gem 'pg'
gem 'rake'
gem 'unicorn'
gem 'qx', git: 'https://github.com/jayrbolton/ruby-qx.git'
gem 'param_validation', git: 'https://github.com/jayrbolton/ruby-param-validation.git'
gem 'rack-rest_api_versioning'
gem 'bcrypt'
gem 'jwt'
gem 'sinatra-cross_origin'
gem 'chronic'

group :development, :test do
  gem 'dotenv'
  gem 'rerun'
  gem 'pry'
end

